spring.application.name=spring-data
spring.datasource.url=jdbc:mysql://localhost:3306/springboot_test_tables
spring.datasource.username = root
spring.datasource.password = erikazr
spring.datasource.driver.class=com.mysql.jdbc.Driver